# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import face_detection_pb2 as face__detection__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in face_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaceDetectionServiceStub(object):
    """Опис сервісу FaceDetectionService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateFace = channel.unary_unary(
                '/face_detection.FaceDetectionService/ValidateFace',
                request_serializer=face__detection__pb2.FaceValidationRequest.SerializeToString,
                response_deserializer=face__detection__pb2.FaceValidationResponse.FromString,
                _registered_method=True)


class FaceDetectionServiceServicer(object):
    """Опис сервісу FaceDetectionService
    """

    def ValidateFace(self, request, context):
        """Метод для перевірки валідності обличчя
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateFace': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateFace,
                    request_deserializer=face__detection__pb2.FaceValidationRequest.FromString,
                    response_serializer=face__detection__pb2.FaceValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'face_detection.FaceDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('face_detection.FaceDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaceDetectionService(object):
    """Опис сервісу FaceDetectionService
    """

    @staticmethod
    def ValidateFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_detection.FaceDetectionService/ValidateFace',
            face__detection__pb2.FaceValidationRequest.SerializeToString,
            face__detection__pb2.FaceValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
