# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face_detection.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'face_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x61\x63\x65_detection.proto\x12\x0e\x66\x61\x63\x65_detection\"&\n\x15\x46\x61\x63\x65ValidationRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\";\n\x16\x46\x61\x63\x65ValidationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2u\n\x14\x46\x61\x63\x65\x44\x65tectionService\x12]\n\x0cValidateFace\x12%.face_detection.FaceValidationRequest\x1a&.face_detection.FaceValidationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACEVALIDATIONREQUEST']._serialized_start=40
  _globals['_FACEVALIDATIONREQUEST']._serialized_end=78
  _globals['_FACEVALIDATIONRESPONSE']._serialized_start=80
  _globals['_FACEVALIDATIONRESPONSE']._serialized_end=139
  _globals['_FACEDETECTIONSERVICE']._serialized_start=141
  _globals['_FACEDETECTIONSERVICE']._serialized_end=258
# @@protoc_insertion_point(module_scope)
